### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sfan5** [sfan5/secretlounge-ng#1]
features: 
* ~~`>>>/g/` to link to related bots in the same "network"~~
* ~~automatic filtering of group invite links~~ (nobody needs this)
* ~~banned sticker packs~~ (maybe later)
* ~~reimplement `/sign`~~
* ~~some way to do shared bans~~

bug / behaviour fixes:
* ~~don't flush sqlite db on every change~~
* ~~`/stop` isn't instant due to the queue~~
* ~~check blacklist status in `user_join()`~~

**Comment by RaymondSchnyder** [comment]
I would like to have a feature to specifiy a "nickname" i could set in an anonymous chat.
maybe like that

<fteven> i like traps

**Comment by astravexton** [comment]
add `/rules`
~~add `/uncooldown`~~
