### ISSUE TITLE
How can i set this up with cron or systemctl/systemd?

### ISSUE THREAD

**Issue by Mrs-Feathers** [sfan5/secretlounge-ng#15]
i want to keep this running in the background for my telegram chat network i have going.. the server reboots sometimes for updates.. everything is completely automated so i can't run the script myself every time it reboots.. and it doesn't seem to know where the libraries are or what "threading" is when i run it with systemctl.. but runs completely fine when i run the script myself.

**Comment by sfan5** [comment]
Well not much different from any other service, this works for me:
<pre>
[Unit]
Description=secretlounge Bot
After=network.target

[Service]
Type=simple
User=ubuntu
WorkingDirectory=/home/ubuntu/secretlounge-ng
ExecStart=/usr/bin/python3 secretlounge-ng

[Install]
WantedBy=multi-user.target
</pre>

**Comment by Mrs-Feathers** [comment]
not sure why but that doesn't work for me. it keeps erroring out... like it doesn't see the libraries when i run it as a service and only seems to work when i run it directly from typing it in the console
