### ISSUE TITLE
Rust?

### ISSUE THREAD

**Issue by cactushydrocodone** [sfan5/secretlounge-ng#2]
Hello dear individual of the universe,

I wanted to ask the question as another human beeing if this rewrite is gonna be in rust later, as javascript is not "a real language" used by intellectuals as we are.
Please consider replying to this issue if you have the time and effort

Friendly Greetings

George R.R. Rust Martin

**Comment by sfan5** [comment]
> as javascript is not "a real language" 

6/10 shitpost
