### ISSUE TITLE
Persistent queuing error

### ISSUE THREAD

**Issue by pumacepato** [sfan5/secretlounge-ng#21]
I've been getting this wonderful error:
![Screenshot_20200719-125226__01](https://user-images.githubusercontent.com/68516172/87883838-05b66f00-c9bf-11ea-9138-31a20f439177.jpg)
Apparently this is causing new users to not receive anything from the bot and will be spit out for every message sent by current users. Everything is up to date. I have not modified the code. Any ideas?

**Comment by sfan5** [comment]
There is invalid data in your database, `lastActive` should never be None.
I suggest just fixing the wrong data and you should never see this error again: `UPDATE users SET lastActive = '1970-01-01 01:00:00' WHERE lastActive IS NULL;`
