### ISSUE TITLE
Poll support

### ISSUE THREAD

**Issue by sobornostea** [sfan5/secretlounge-ng#29]
Are there technical limitations that make it impossible to support polls ? If yes, that's sad...
If not, i would be interested in helping ^^

**Comment by sfan5** [comment]
Yes that's the case, [`sendPoll`](https://core.telegram.org/bots/api#sendpoll) creates a new poll that is unique for every user it is called on (and so does[`copyMessage`](https://core.telegram.org/bots/api#copymessage)).

**Comment by sobornostea** [comment]
Would it be possible to recreate a poll with the same characteristics ? And then forward it using [`forwardMessage`](https://core.telegram.org/bots/api#forwardmessage) ? Or does it create a unique poll again...

**Comment by sfan5** [comment]
That sounds like it'd work. Only issue with it is that Telegram heavily throttles forwards, but that's in general.

**Comment by sobornostea** [comment]
Hi, I've implemented poll support with the `forwardMessage` method, are you interested by this feature ?
