### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by turannul** [sfan5/secretlounge-ng#38]
$ ./secretlounge-ng
 /usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDe pendencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't matc a supported version! warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supp orted Traceback (most recent call last): File "./secretlounge-ng", line 9, in <module> import src.core as core File "/home/ubuntu/averagesbot/src/core.py", line 149, in <modul class Receiver(): File "/home/ubuntu/averagesbot/src/core.py", line 154, in Receiv er def delete(msids: list[int]): TypeError: type' object is not subscriptable

* Ubuntu 20.04 LTS | AWS

**Comment by sfan5** [comment]
Your python version seems to be too old. You need at least 3.5 but 3.8 (which Ubuntu 20.04 should have) definitely works.

**Comment by turannul** [comment]
> Your python version seems to be too old. You need at least 3.5 but 3.8 (which Ubuntu 20.04 should have) definitely works.

i have python 3.8.10 i installed requirements

**Comment by sfan5** [comment]
Judging from your error, you don't or your installation is otherwise broken.
