### ISSUE TITLE
Karma totals can be used by moderators to identify users

### ISSUE THREAD

**Issue by solarbearcub** [sfan5/secretlounge-ng#41]
Users are pseudonymous, they're assigned a generated ID every day to preserve eventual privacy over a number of days. 

Currently karma totals are loosely visible to mods and admins, these totals can be (and sometimes are) used to track a given user between generated IDs, across multiple days. If a user has signed at any point any moderator can identify their messages at any point into the future; I don't know how probable this is but the information available to moderators does make it possible to do this.

Hiding the karma total would prevent this. If karma is important information for mods returning just the sign (negative, zero, positive) would be preferable.

<details>
    <summary><h4>Examples<h4></summary>

![image](https://user-images.githubusercontent.com/97406365/225727974-ffe25916-8695-402a-8daf-da089a6df56b.png)

![image](https://user-images.githubusercontent.com/97406365/225730630-b9743461-824f-43f5-a5db-98e3d83b7bb4.png)
</details>

**Comment by sfan5** [comment]
This is indeed an issue.
I think karma is very valuable for mods and `+`, zero or `-` is probably too little information. Differentiating by e.g. 0, 10, 50+ should still be useful enough without being too risky.

**Comment by solarbearcub** [comment]
Sure, that's understandable, as long as the number of users within each band is high then that would still effectively reduce surface area for identification. This would probably necessitate a fixed number of buckets rather than dynamically ranging it, since some users will shoot up or down and then become immediately identifiable as the sole user in eg the `> 400` point bracket.

I'm happy to write a PR to address this. You have access to point totals, would something like 6 ranges centered around zero work? Something like `< -20`, `< -10`, `< 0`, `> 0`, `> 10`, `> 20`?

**Comment by sfan5** [comment]
I'd use -50, -10, 0, 10, 50 but sounds fine otherwise. If you want to write a PR that'd be nice.

**Comment by solarbearcub** [comment]
Sorry about the delay, little PR is up now.
