### ISSUE TITLE
Replace depreated `crypt`

### ISSUE THREAD

**Issue by sfan5** [sfan5/secretlounge-ng#46]
https://github.com/fedora-python/crypt_r looks promising

**Comment by NaruFGT** [comment]
This might be a big ask but is there any way that we could try to call the system's crypt library if it has one before resorting to this one?

**Comment by sfan5** [comment]
I can simply try importing `crypt` before `r_crypt`, if that's what you mean.
Anything more than that (e.g. CFFI) would be unreasonable.

**Comment by NaruFGT** [comment]
Thanks for the response, yeah CFFI was exactly what I had in mind, though I'm not familiar enough with python to know the ins and outs of how to use it. 
And yeah, I can understand why that's beyond what you'd want to try to maintain. Thanks for considering.
